### ISSUE TITLE
为什么会存在解码问题？

### ISSUE THREAD

**Issue by xshkdjsh** [huntingzhu/webcrawler#2]
Traceback (most recent call last):
  File "F:/PY/20171006webdriber.py", line 88, in <module>
    main()
  File "F:/PY/20171006webdriber.py", line 52, in main
    girls.write(result_bf)
UnicodeEncodeError: 'gbk' codec can't encode character '\u2207' in position 86907: illegal multibyte sequence
>>>

**Comment by fff2zrx** [comment]
加上编码方式参数，with open("./output/rawfile/noscript_meta.txt", 'w',encoding='utf-8') as noscript_meta
